# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Python package

on: [push, pull_request]

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Dockerfile
      run: |
        docker build -t reuse .
    - name: Run Docker image against source
      run: |
        docker run -v "$(pwd):/data" reuse
